#ifndef AVEL_SIZES_HPP
#define AVEL_SIZES_HPP

//=========================================================
// Vectors sizes
//=========================================================

#if defined(AVEL_AVX512BW)
    #define AVEL_NATURAL_WIDTH_8U 64
    #define AVEL_NATURAL_WIDTH_16U 32
    #define AVEL_NATURAL_WIDTH_32U 16
    #define AVEL_NATURAL_WIDTH_64U 8

    #define AVEL_NATURAL_WIDTH_8I 32
    #define AVEL_NATURAL_WIDTH_16I 16
    #define AVEL_NATURAL_WIDTH_32I 16
    #define AVEL_NATURAL_WIDTH_64I 8

    #define AVEL_NATURAL_WIDTH_32F 16
    #define AVEL_NATURAL_WIDTH_64F 8



    #define AVEL_MAX_WIDTH_8U 64
    #define AVEL_MAX_WIDTH_16U 32
    #define AVEL_MAX_WIDTH_32U 16
    #define AVEL_MAX_WIDTH_64U 8

    #define AVEL_MAX_WIDTH_8I 64
    #define AVEL_MAX_WIDTH_16I 32
    #define AVEL_MAX_WIDTH_32I 16
    #define AVEL_MAX_WIDTH_64I 8

    #define AVEL_MAX_WIDTH_32F 16
    #define AVEL_MAX_WIDTH_64F 8

#elif defined(AVEL_AVX512F)
    #define AVEL_NATURAL_WIDTH_8U 32
    #define AVEL_NATURAL_WIDTH_16U 16
    #define AVEL_NATURAL_WIDTH_32U 16
    #define AVEL_NATURAL_WIDTH_64U 8

    #define AVEL_NATURAL_WIDTH_8I 32
    #define AVEL_NATURAL_WIDTH_16I 16
    #define AVEL_NATURAL_WIDTH_32I 16
    #define AVEL_NATURAL_WIDTH_64I 8

    #define AVEL_NATURAL_WIDTH_32F 16
    #define AVEL_NATURAL_WIDTH_64F 8



    #define AVEL_MAX_WIDTH_8U 64
    #define AVEL_MAX_WIDTH_16U 32
    #define AVEL_MAX_WIDTH_32U 16
    #define AVEL_MAX_WIDTH_64U 8

    #define AVEL_MAX_WIDTH_8I 64
    #define AVEL_MAX_WIDTH_16I 32
    #define AVEL_MAX_WIDTH_32I 16
    #define AVEL_MAX_WIDTH_64I 8

    #define AVEL_MAX_WIDTH_32F 16
    #define AVEL_MAX_WIDTH_64F 8

#elif defined(AVEL_AVX2)
    #define AVEL_NATURAL_WIDTH_8U 32
    #define AVEL_NATURAL_WIDTH_16U 16
    #define AVEL_NATURAL_WIDTH_32U 8
    #define AVEL_NATURAL_WIDTH_64U 4

    #define AVEL_NATURAL_WIDTH_8I 32
    #define AVEL_NATURAL_WIDTH_16I 16
    #define AVEL_NATURAL_WIDTH_32I 8
    #define AVEL_NATURAL_WIDTH_64I 4

    #define AVEL_NATURAL_WIDTH_32F 8
    #define AVEL_NATURAL_WIDTH_64F 4



    #define AVEL_MAX_WIDTH_8U 32
    #define AVEL_MAX_WIDTH_16U 16
    #define AVEL_MAX_WIDTH_32U 8
    #define AVEL_MAX_WIDTH_64U 4

    #define AVEL_MAX_WIDTH_8I 32
    #define AVEL_MAX_WIDTH_16I 16
    #define AVEL_MAX_WIDTH_32I 8
    #define AVEL_MAX_WIDTH_64I 4

    #define AVEL_MAX_WIDTH_32F 8
    #define AVEL_MAX_WIDTH_64F 4

#elif defined(AVEL_AVX)
    #define AVEL_NATURAL_WIDTH_8U 16
    #define AVEL_NATURAL_WIDTH_16U 8
    #define AVEL_NATURAL_WIDTH_32U 4
    #define AVEL_NATURAL_WIDTH_64U 2

    #define AVEL_NATURAL_WIDTH_8I 16
    #define AVEL_NATURAL_WIDTH_16I 8
    #define AVEL_NATURAL_WIDTH_32I 4
    #define AVEL_NATURAL_WIDTH_64I 2

    #define AVEL_NATURAL_WIDTH_32F 8
    #define AVEL_NATURAL_WIDTH_64F 4



    #define AVEL_MAX_WIDTH_8U 32
    #define AVEL_MAX_WIDTH_16U 16
    #define AVEL_MAX_WIDTH_32U 8
    #define AVEL_MAX_WIDTH_64U 4

    #define AVEL_MAX_WIDTH_8I 32
    #define AVEL_MAX_WIDTH_16I 16
    #define AVEL_MAX_WIDTH_32I 8
    #define AVEL_MAX_WIDTH_64I 4

    #define AVEL_MAX_WIDTH_32F 8
    #define AVEL_MAX_WIDTH_64F 4

#elif defined(AVEL_SSE2) | defined(AVEL_NEON)
    #define AVEL_NATURAL_WIDTH_8U 16
    #define AVEL_NATURAL_WIDTH_16U 8
    #define AVEL_NATURAL_WIDTH_32U 4
    #define AVEL_NATURAL_WIDTH_64U 2

    #define AVEL_NATURAL_WIDTH_8I 16
    #define AVEL_NATURAL_WIDTH_16I 8
    #define AVEL_NATURAL_WIDTH_32I 4
    #define AVEL_NATURAL_WIDTH_64I 2

    #define AVEL_NATURAL_WIDTH_32F 4
    #define AVEL_NATURAL_WIDTH_64F 2



    #define AVEL_MAX_WIDTH_8U 16
    #define AVEL_MAX_WIDTH_16U 8
    #define AVEL_MAX_WIDTH_32U 4
    #define AVEL_MAX_WIDTH_64U 2

    #define AVEL_MAX_WIDTH_8I 16
    #define AVEL_MAX_WIDTH_16I 8
    #define AVEL_MAX_WIDTH_32I 4
    #define AVEL_MAX_WIDTH_64I 2

    #define AVEL_MAX_WIDTH_32F 4
    #define AVEL_MAX_WIDTH_64F 2

#endif

//=========================================================
// Mask vectors alignment
//=========================================================

#if defined(AVEL_AVX512VL)
    #define AVEL_MASK_ALIGNMENT_32X8U 4
    #define AVEL_MASK_ALIGNMENT_16X16U 2
    #define AVEL_MASK_ALIGNMENT_8X32U 1
    #define AVEL_MASK_ALIGNMENT_4X64U 1

    #define AVEL_MASK_ALIGNMENT_32X8I 4
    #define AVEL_MASK_ALIGNMENT_16X16I 2
    #define AVEL_MASK_ALIGNMENT_8X32I 1
    #define AVEL_MASK_ALIGNMENT_4X64I 1

    #define AVEL_MASK_ALIGNMENT_8X32F 1
    #define AVEL_MASK_ALIGNMENT_4X64F 1


    #define AVEL_MASK_ALIGNMENT_16X8U 2
    #define AVEL_MASK_ALIGNMENT_8X16U 1
    #define AVEL_MASK_ALIGNMENT_4X32U 1
    #define AVEL_MASK_ALIGNMENT_2X64U 1

    #define AVEL_MASK_ALIGNMENT_16X8I 2
    #define AVEL_MASK_ALIGNMENT_8X16I 1
    #define AVEL_MASK_ALIGNMENT_4X32I 1
    #define AVEL_MASK_ALIGNMENT_2X64I 1

    #define AVEL_MASK_ALIGNMENT_4X32F 1
    #define AVEL_MASK_ALIGNMENT_2X64F 1
#endif

#if defined(AVEL_AVX512BW) & defined(AVEL_AVX512VL)
    #define AVEL_MASK_ALIGNMENT_64X8U 8
    #define AVEL_MASK_ALIGNMENT_3216U 4

    #define AVEL_MASK_ALIGNMENT_64X8I 8
    #define AVEL_MASK_ALIGNMENT_32X16I 4
#endif

#if defined(AVEL_AVX512BW) & !defined(AVEL_AVX512VL)
    #define AVEL_MASK_ALIGNMENT_64X8U 64
    #define AVEL_MASK_ALIGNMENT_3216U 64

    #define AVEL_MASK_ALIGNMENT_64X8I 64
    #define AVEL_MASK_ALIGNMENT_32X16I 64
#endif

#if defined(AVEL_AVX512F)
    #define AVEL_MASK_ALIGNMENT_16X32U 4
    #define AVEL_MASK_ALIGNMENT_8X64U 2

    #define AVEL_MASK_ALIGNMENT_16X32I 2
    #define AVEL_MASK_ALIGNMENT_8X64I 1

    #define AVEL_MASK_ALIGNMENT_16X32F 4
    #define AVEL_MASK_ALIGNMENT_8X64F 2
#endif

#if defined(AVEL_AVX) & !defined(AVEL_AVX512VL)
    #define AVEL_MASK_ALIGNMENT_32X8U 32
    #define AVEL_MASK_ALIGNMENT_16X16U 32
    #define AVEL_MASK_ALIGNMENT_8X32U 32
    #define AVEL_MASK_ALIGNMENT_4X64U 32

    #define AVEL_MASK_ALIGNMENT_32X8I 32
    #define AVEL_MASK_ALIGNMENT_16X16I 32
    #define AVEL_MASK_ALIGNMENT_8X32I 32
    #define AVEL_MASK_ALIGNMENT_4X64I 32

    #define AVEL_MASK_ALIGNMENT_8X32F 32
    #define AVEL_MASK_ALIGNMENT_4X64F 32
#endif

#if defined(AVEL_SSE2) & !defined(AVEL_AVX512VL)
    #define AVEL_MASK_ALIGNMENT_16X8U 16
    #define AVEL_MASK_ALIGNMENT_8X16U 16
    #define AVEL_MASK_ALIGNMENT_4X32U 16
    #define AVEL_MASK_ALIGNMENT_2X64U 16

    #define AVEL_MASK_ALIGNMENT_16X8I 16
    #define AVEL_MASK_ALIGNMENT_8X16I 16
    #define AVEL_MASK_ALIGNMENT_4X32I 16
    #define AVEL_MASK_ALIGNMENT_2X64I 16

    #define AVEL_MASK_ALIGNMENT_4X32F 16
    #define AVEL_MASK_ALIGNMENT_2X64F 16

#endif

#endif //AVEL_SIZES_HPP
