name: AVEL Tests
run-name: ${{ github.actor }} is running AVEL's tests
on: [push]
jobs:
  AVEL-x86-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Intel SDE
        uses: petarpetrovt/setup-sde@v2.1
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install gtest manually
        run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - run: python3 run_avel_tests.py -A"x86"
  AVEL-ARM-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not yet implemented"
