name: AVEL Tests
run-name: ${{ github.actor }} is running AVEL's tests
on:
  push:
    paths:
      - 'tests/**'
      - 'include/**'
      - '.github/workflows/**'
      - 'run_avel_tests.py'
      - 'CMakeLists.txt'
jobs:
  AVEL-x86-tests-GCC-9:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure g++9 is Installed
        run: sudo apt-get install g++-9 -y
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Intel SDE
        run: wget https://downloadmirror.intel.com/788820/sde-external-9.27.0-2023-09-13-lin.tar.xz &&
             tar -xf sde-external-9.27.0-2023-09-13-lin.tar.xz
      - name: Run AVEL test script
        run: python3 run_avel_tests.py -A"x86" -C"/usr/bin/g++-9" -L"./sde-external-9.27.0-2023-09-13-lin/sde64 -icl -- <exec>"
  AVEL-x86-tests-Clang-11:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure clang++-11 is Installed
        run: sudo apt-get install clang++-11 -y
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Intel SDE
        run: wget https://downloadmirror.intel.com/788820/sde-external-9.27.0-2023-09-13-lin.tar.xz &&
             tar -xf sde-external-9.27.0-2023-09-13-lin.tar.xz
      - name: Run AVEL test script
        run: python3 run_avel_tests.py -A"x86" -C"/usr/bin/clang++-11" -L"./sde-external-9.27.0-2023-09-13-lin/sde64 -icl -- <exec>"

#  AVEL-ARM-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Not yet implemented"
